--- #YAML:1.0
name:               Config-YAML-Tiny
version:            1.42.0
abstract:           simple reading and writing of YAML-formatted
author:
    - Timothy Appnel <tima@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    YAML::Tiny:  1.12
resources:
    repository:  http://github.com/tima/perl-config-yaml-tiny
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
